server:
  port: 8090

spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: Wh2018212168
    url: jdbc:mysql://47.97.217.191:3306/Eunomia?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource # 自定义数据源
    servlet:
      multipart:
        max-file-size: -1
        max-request-size: -1

file:
  path: ./file

cbs:
  imagesPath: file:/D:/Idea Project/xinan-competition/evidence


